chore(docs): add warning in README
prisma/reflector pull request #7
Opened 2022-03-14 12:41 UTC by Jolg42

2022-03-14 14:34 UTC, jasonkuhrt requested changes

2022-03-14 14:34 UTC, jasonkuhrt commented on README.md
> +⚠️ **Warning: This is an internal package, which is owned by the Prisma Developer Productivity Team** ⚠️
```suggestion
Utilities for meta-level interactions with the Prisma toolkit in Node.js.

⚠️ **Warning: This is not a formal Prisma product like `prisma`, `@prisma/client`, etc. If you get value from it great, but there are no guarantees about the vision of this package. That said this package will honour semantic versioning. It is used within Prisma in some projects but also outside such as `nexus-prisma`.** ⚠️
```

2022-03-14 15:47 UTC, Jolg42 commented on README.md
> +⚠️ **Warning: This is an internal package, which is owned by the Prisma Developer Productivity Team** ⚠️
Nice!

2022-03-16 18:05 UTC, jasonkuhrt approved these changes
LGTM 🚀 !

2022-03-16 18:06 UTC, merged